import * from "../src/utils.ab"

pub fun assert(condition: Bool, message: Text): Null {
    /// Asserts that a condition is true; otherwise, prints an error message and exits.
    if not condition {
        eprintf_colored("Assertion failed: {message}\n", 31)
        trust $ exit 1 $
    }
}

pub fun assert_eq(actual: Text, expected: Text, message: Text): Null {
    /// Asserts that two texts are equal; otherwise, prints an error message and exits.
    if expected != actual {
        eprintf_colored("Assertion failed: {message}\nExpected: {expected}\nActual: {actual}\n", 31)
        trust $ exit 1 $
    }
}

pub fun assert_ne(actual: Text, not_expected: Text, message: Text): Null {
    /// Asserts that two texts are not equal; otherwise, prints an error message and exits.
    if not_expected == actual {
        eprintf_colored("Assertion failed: {message}\nNot Expected: {not_expected}\nActual: {actual}\n", 31)
        trust $ exit 1 $
    }
}
